- hosts: history_server
  remote_user: hadoop
  tasks:
    - name: stop history server
      command: mr-jobhistory-daemon.sh start historyserver
    - name: stop history server
      command: yarn-daemon.sh start timelineserver