- name: Delete the temporary directory
  file: path={{tmp_path}} state=absent

- name: Create the temporary directory
  file: path={{tmp_path}} state=directory owner={{install_user}} group={{install_user}}

- name: Delete the temporary directory
  file: path={{install_path}} state=absent

- name: Create the temporary directory
  file: path={{install_path}} state=directory owner={{install_user}} group={{install_user}}

- name: Unarchive the jar package for customization
  unarchive:
    src: '{{package_path}}/{{package_name}}'
    dest: '{{tmp_path}}/'

- name: replace the application.yml
  template:
    dest: '{{tmp_path}}/BOOT-INF/classes/application.yml'
    src: application.yml.j2

- name: replace the logback-spring.xml
  template:
    dest: '{{tmp_path}}/BOOT-INF/classes/logback-spring.xml'
    src: logback-spring.xml.j2

- name: Archive again after customization
  shell: source /etc/profile;jar cvf '{{install_path}}/{{package_name}}' .
  args:
    chdir: '{{tmp_path}}'

- name: Delete the temporary directory
  file: path={{tmp_path}} state=absent