- name: mkdir '{{zookeeper_install_path}}'
  file: path='{{zookeeper_install_path}}' state=directory mode=0755  owner=hadoop group=hadoop

- name: mkdir '{{zookeeper_datadir}}'
  file: path='{{zookeeper_datadir}}' state=directory mode=0755  owner=hadoop group=hadoop

- name: unarchive hadoop
  unarchive: src='{{zookeeper_package_path}}' dest='{{zookeeper_install_path}}' owner=hadoop group=hadoop

- name: copy zoo.cfg
  copy: src=zoo.cfg.j2 dest='{{zookeeper_confdir}}/zoo.cfg'  owner=hadoop group=hadoop

- name: copy myid
  copy: src=zoo.cfg.j2 dest='{{zookeeper_confdir}}/zoo.cfg'  owner=hadoop group=hadoop

- name: set_up zookeeper ENV
  template: src=hadoop.sh.j2 dest='{{ENV_FILE_DIR}}/hadoop.sh' owner=root group=root mode=0755
  become: yes
  become_user: root
  become_method: sudo

- name: soure '{{ENV_FILE}}'
  shell: source '{{ENV_FILE}}'