- name: mkdir directory
  file: path='{{JDK_SETUP_DIRECTORY}}' state=directory mode=0755
# - name: copy & unzip '{{JDK_TAR_PATH}}'
#   unarchive: src='{{JDK_TAR_PATH}}' dest='{{JDK_SETUP_DIRECTORY}}'


- name: create jvm_env file
  file: path='{{ENV_FILE}}' mode=0755 owner=root  group=root

# - name: set_up JDK ENV
#   lineinfile:
#     dest: '{{ENV_FILE}}'
#     insertafter: '{{item.position}}'
#     line: '{{item.value}}'
#     state: present
#   with_items:
#     - {position: EOF, value: "\n"}
#     - {position: EOF, value: "export JAVA_HOME={{JDK_SETUP_DIRECTORY}}/{{JDK_VERSION}}"}
#     - {position: EOF, value: "export PATH=$PATH:JAVA_HOME/bin"}

# - name: soure '{{ENV_FILE_PARENT}}'
#   shell: source '{{ENV_FILE_PARENT}}'