- name: mkdir directory
  file: path='{{JDK_SETUP_DIRECTORY}}' state=directory mode=0755  owner=root group=root

- name: copy clear.sh
  copy: src='clear.sh.j2' dest='{{JDK_SETUP_DIRECTORY}}/clear.sh' owner=root group=root mode=0755

- name: execute clear.sh
  command: sudo . '{{JDK_SETUP_DIRECTORY}}'/clear.sh

- name: delete clear.sh
  command: rm -rf '{{JDK_SETUP_DIRECTORY}}'/clear.sh

- name: copy & unzip '{{JDK_TAR_PATH}}'
  unarchive: src='{{JDK_TAR_PATH}}' dest='{{JDK_SETUP_DIRECTORY}}' owner=root group=root

- name: set_up JDK ENV
  template: src=jvm.sh.j2 dest='{{ENV_FILE_DIR}}/jvm.sh' owner=root group=root mode=0755

- name: soure '{{ENV_FILE}}'
  shell: source '{{ENV_FILE}}'